server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tjut_reservation?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mapper/*.xml

wechat:
  appid: wx1e6fdf0c98dc8a82
  secret: 125930810d426c18dc8706ab8c10166b

token:
  time: 60*60*24*7
  sign: HANZOY@SIPC_WECHAT_reservation
